version: 2

multi-ecosystem-groups:
  weekly-dependencies:
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "UTC"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-dependencies"
